version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    command: flask run --host=0.0.0.0
    environment:
      - FLASK_APP=/code/backend/ui/poketest/wsgi.py
      - FLASK_DEBUG=1
      - FLASK_ENV=development
      - PYTHONPATH=/code
      - api=https://pokeapi.co/api/v2/berry
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/code/backend